In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
# We start by reading the class.txt file with the full database with labels.
classes = pd.read_table("../data/CATALINA_PHOT/class.txt")
classes[classes.duplicated('#CRTS ID')]

,#CRTS ID,RA (J2000),Dec (J2000),UT Date,Mag,CSS images,SDSS,Others,Followed,Last,LC,FC,Classification
31,CSS131012:000918-194224,2.3262,-19.70678,20131012.22,13.89,1310120180014101233,no,10123,no,2016-10-22,10123,yes,HPM LHS_105

In [3]:
ii = classes['CSS images']==1310120180014101233
classes[ii]

,#CRTS ID,RA (J2000),Dec (J2000),UT Date,Mag,CSS images,SDSS,Others,Followed,Last,LC,FC,Classification
30,CSS131012:000918-194224,2.3262,-19.70678,20131012.22,13.89,1310120180014101233,no,10123,no,2016-10-22,10123,yes,HPM LHS_105
31,CSS131012:000918-194224,2.3262,-19.70678,20131012.22,13.89,1310120180014101233,no,10123,no,2016-10-22,10123,yes,HPM LHS_105

In [4]:
print(len(np.unique(classes['#CRTS ID'])))
classes[:3]

5539

,#CRTS ID,RA (J2000),Dec (J2000),UT Date,Mag,CSS images,SDSS,Others,Followed,Last,LC,FC,Classification
0,CSS120828:000010-215515,0.04323,-21.92087,20120828.38,17.02,1208280210014111715,no,11171,no,2016-10-22,11171,yes,Var
1,CSS100910:000025+332543,0.10280,33.42861,20100910.42,15.85,1009101320014148188,yes,14818,no,2016-11-05,14818,yes,"CV SDSS mag 20,5"
2,CSS101127:000130+050624,0.37695,5.10657,20101127.21,15.68,1011271040014129121,no,12912,yes,2016-11-06,12912,yes,"CV mag 20,0"

In [23]:
# We create a new column with the trasient class name
n_elements  = len(classes)
classification = []
for i in range(n_elements):
    classification.append(classes['Classification'][i].split()[0])
classes['class'] = classification
classes = classes.rename(columns={"CSS images":"transID"})
classes = classes.set_index("transID")
print(len(classes.index))
print(len(np.unique(classes.index)))
classes[:10]

# look for transID in orphan data
cuenta = open('cuenta_en_orph.sh', 'w')
for i in classes.index:
    cuenta.write("grep {} *.orph |wc -l\n".format(i))
cuenta.close()

5540
5539

In [108]:
# With the 'CSS_images' we have to link to the 'dbID' that is provided in the *.out 
# files. That's why we read them here:

In [24]:
out_files  = glob.glob("../data/CATALINA_PHOT/*.out")
print(out_files)

['../data/CATALINA_PHOT/input1.out', '../data/CATALINA_PHOT/input10.out', '../data/CATALINA_PHOT/input11.out', '../data/CATALINA_PHOT/input12.out', '../data/CATALINA_PHOT/input13.out', '../data/CATALINA_PHOT/input14.out', '../data/CATALINA_PHOT/input15.out', '../data/CATALINA_PHOT/input16.out', '../data/CATALINA_PHOT/input17.out', '../data/CATALINA_PHOT/input18.out', '../data/CATALINA_PHOT/input19.out', '../data/CATALINA_PHOT/input2.out', '../data/CATALINA_PHOT/input20.out', '../data/CATALINA_PHOT/input21.out', '../data/CATALINA_PHOT/input22.out', '../data/CATALINA_PHOT/input23.out', '../data/CATALINA_PHOT/input24.out', '../data/CATALINA_PHOT/input25.out', '../data/CATALINA_PHOT/input26.out', '../data/CATALINA_PHOT/input27.out', '../data/CATALINA_PHOT/input28.out', '../data/CATALINA_PHOT/input3.out', '../data/CATALINA_PHOT/input4.out', '../data/CATALINA_PHOT/input5.out', '../data/CATALINA_PHOT/input6.out', '../data/CATALINA_PHOT/input7.out', '../data/CATALINA_PHOT/input8.out', '../data/CATALINA_PHOT/input9.out']

In [25]:
out_data = pd.read_table(out_files[0], sep=' ',header=None, names=['transID', 'dbID', 'mag_out', 'ra_out', 'dec_out'])
for i in range(1,len(out_files)):
    tmp_data = pd.read_table(out_files[i], sep=' ',header=None, names=['transID', 'dbID', 'mag_out', 'ra_out', 'dec_out'])
    out_data = pd.concat([out_data, tmp_data])
out_data = out_data.set_index("transID")
#print(len(out_data))
print(len(out_data.index))
print('unicos', len(np.unique(out_data['dbID'])))
out_data[:10]

# look for dbID in phot data
cuenta = open('cuenta_en_phot.sh', 'w')
for i in out_data['dbID']:
    cuenta.write("grep {} *.phot |wc -l\n".format(i))
cuenta.close()
#out_data['transID']

4280
unicos 4046

In [ ]:
# look for the link 'CSS images'->'dbID'
n_elements  = len(classes)
dbID = []
for i in range(n_elements):
    classification.append(classes['Classification'][i].split()[0])
classes['class'] = classification

In [26]:
idtrans_orph = np.loadtxt('../data/CATALINA_PHOT/ID_trans_para_cuenta_en_orph', dtype=int)
n_orph = np.loadtxt('../data/CATALINA_PHOT/conteo_orph', dtype=int)
print(len(idtrans_orph))
iddb_phot = np.loadtxt('../data/CATALINA_PHOT/ID_DB_para_cuenta_en_phot', dtype=int)
n_phot = np.loadtxt('../data/CATALINA_PHOT/conteo_phot', dtype=int)
print(len(n_phot))
idtrans_orph[0:10]

5540
4280

array([1208280210014111715, 1009101320014148188, 1011271040014129121,
       1607091210014124380, 1109261070014122864, 1511091090014127873,
       1111020260014102295, 1111300260014103252, 1511191320014127170,
       1110061260014124074])

In [32]:
curvas_existentes = 0
curvas_inexistentes = 0
n_esperadas = len(idtrans_orph)
print(n_esperadas)
pp=0
for i in range(n_esperadas): # busco en todas los indices de las transientes de entrada
    #print('ENTRA', idtrans_orph[i])
    if idtrans_orph[i] in out_data.index: # miro si este indice de transiente tiene un IDdb asociado
        iddb  = np.int_(out_data.loc[idtrans_orph[i]]['dbID'])
        if np.isscalar(iddb): # pude que un valor de idtrans sea uno solo en iddb
            #print('\t dbID', iddb)
            ii = np.where(iddb==iddb_phot)[0]
            if n_phot[ii][0] > 0: # busco este IDdb in phot
                #print('\t NOT ORPHAN {}'.format(n_phot[ii][0]))
                curvas_existentes +=1
            else:
                curvas_inexistentes +=1
        else: # pero tambien puede ser que un valor de idtrans sea varios in iddb.

            n_in_phot = n_phot[np.in1d(iddb_phot, iddb)]
            if n_in_phot[0]==n_in_phot[1]:
                print(idtrans_orph[i], iddb, n_in_phot)
                pp+=1
            if np.all(n_in_phot==0): # busco este IDdb in phot
                curvas_inexistentes +=1
            else:
                curvas_existentes +=1
 
        #ii = ==iddb_phot
    elif n_orph[i]>0: # si no esta en phot miro si esta en orph
        #print('\t ORPHAN {}'.format(n_orph[i]))
        curvas_existentes +=1
    else:
        curvas_inexistentes +=1
print(curvas_existentes, curvas_inexistentes, curvas_existentes+curvas_inexistentes)
print(pp)

5540
1310120180014101233 [3019002005376 3019002005376] [51 51]
1310120180014101233 [3019002005376 3019002005376] [51 51]
712181350024142260 [1135003067050 1135003067050] [0 0]
1211131260074105573 [1126007006403 1126007006403] [128 128]
909161010074118793 [2101018003222 2101019003389 2101018003222 2101019003389] [0 0 0 0]
1610131180104104884 [1118010008073 2116026021020] [0 0]
1301151120114110654 [2112028003650 2111028020892 2112028003650 2111028020892] [0 0 0 0]
909170150134129127 [3015017012808 3015018012933 1015013037407 3015017012808 3015018012933] [  0   0 184   0   0]
1312241210134128201 [2121033017540 2121034014137 2121033017540 2121034014137] [0 0 0 0]
1209190090144112412 [3011019014679 3011020016200 1009014012279 3011019014679 3011020016200
 3011019014679 3011020016200] [  0   0 246   0   0   0   0]
1511090150184104648 [1015018006207 3015026022960 3015026022960] [0 0 0]
909281150204138107 [2116051004986 2116052005563 2116051004986 2116052005563] [0 0 0 0]
910230180214124000 [1018021034108 1018021034108 3017028003093] [37 37 22]
910241150234136893 [1115023046499 2116059000135 2115059022214 2116059000135 2115059022214] [0 0 0 0 0]
1412101150244143796 [2116061009088 2116060008314 2116061009088 2116060008314] [0 0 0 0]
811191120264138954 [2113066001219 2113066001219] [0 0]
1403061320334126683 [2131083021496 2131084021976 2131083021496 2131084021976] [0 0 0 0]
1412291150404157125 [2115101029796 2115102029205 2115101029796 2115102029205] [0 0 0 0]
803031210404117636 [2121103002629 2121104002401 2121103002629 2121104002401] [0 0 0 0]
1302181400354146917 [1140035064203 1140035064203] [254 254]
903021490314120932 [1149031024627 1149031024627] [265 265]
712031180464106445 [2117118000598 2116118028742 2117118000598 2116118028742] [0 0 0 0]
1005121520304133272 [1152030056877 1152030056877] [32 32]
1104041150484138263 [2116122008172 2116123007643 2116122008172 2116123007643] [0 0 0 0]
811071120494103889 [2111127022738 2111126019189 2111127022738 2111126019189] [0 0 0 0]
1204161070504138772 [1107050051221 2108128007523 2108128007495] [47 47  1]
1104291230534105550 [1123053007568 1123053007568] [217 217]
1402101660274120416 [1166027031288 1166026035560 1166027031288 1166026035560] [0 0 0 0]
1603270150644120769 [3015090009562 3015090009562] [107 107]
1203250150664136435 [1015066041506 3015092015690] [0 0]
812290090734109439 [2010189002726 2010188002673 2010189002726 2010188002673] [0 0 0 0]
904180210754153893 [2020193007772 3021104044071] [10 10 68 10 68]
805110210754143931 [2020193007772 3021104044071] [10 10 68 10 68]
1305160180764144916 [3017106008003 3017106008003] [130 130]
1303241460584112024 [1146058019781 1146058019781] [27 27]
1605030210794103494 [2022202010580 2022201011372 2022202010580 2022201011372 3023108053793
 3023108053793] [ 0  0  0  0 63 63]
1103301150814122387 [1115081032850 1115081032850] [222 222]
1607081690324112179 [1169033017384 1169033017384] [1 1]
905260150844128133 [3017116065919 3017116065919] [0 0]
905260150844165166 [2015217048837 2014219000832 2015217048837 2014219000832] [0 0 0 0]
1201301010874137575 [1101087046622 2101225006906 2101226007770 2101225006882 2101225006906
 2101226007770 2101225006882] [0 0 0 0 0 0 0]
804050040884106446 [1004087007090 1004088008093 1004087007090 1004088008093 2005225037427
 2005226032984 2005226033014 2005225037427 2005226032984 2005226033014] [0 0 0 0 0 0 0 0 0 0]
1306010120884194298 [1012088121674 1012088121674 2011229020090] [32 32 14]
1405011630424105496 [1163042010035 1163042010035] [55 55]
1306171600474117100 [1160047023203 1160047023203] [11 11]
1110221210884105604 [1121088011456 2120227024162] [41 41]
806100091194116339 [2010305023856 2010306021997 2010305023856 2010306021997] [0 0 0 0]
1010101351004150592 [1135100062402 1135100062402] [68 68]
1107010071244113143 [1007124016110 2008322026481] [58 58]
909151400974133892 [1140097038930 1140097038930] [29 29]
1101151181224113126 [1118122027804 1118122027804] [78 78]
4982 558 5540
51

In [202]:
out_data

                              dbID  mag_out     ra_out   dec_out
transID
1208280210014111715  1021001010444   17.415    0.04331 -21.92086
1009101320014148188  1132001069055   19.742    0.10307  33.42835
1011271040014129121  1104001042684   19.813    0.37714   5.10631
1011271040014129121  2104001014968   18.058    0.37694   5.10679
1607091210014124380  1121001032550   18.444    0.38483  21.22677
1110061260014124074  1126001035357   18.620    1.33744  26.82108
1206191210014107066  1121001005907   21.599    1.39179  20.02357
1609221070014133607  2108002020064   20.968    1.47321   8.43018
1006021180014134943  1118001057162   20.985    1.74870  19.47162
1512020150014110836  1015001015876   20.115    1.81631 -16.10452
1410251320014115813  1132001023848   19.442    1.83111  31.87859
1512031120014116775  1112001023730   21.469    1.92627  12.46893
1011111120014121468  1112001027513   20.332    2.00192  12.65415
1310250040014131234  1004001034329   19.120    2.06686  -3.60581
1310250040014131234  2003002017200   19.371    2.06702  -3.60580
1310250040014131234  3003002003323   20.433    2.06799  -3.60492
1410291210014109021  1121001011647   19.553    2.22777  20.28344
1210211070014111403  1107001017304   18.190    2.26635   6.47271
1210211070014111403  2105003025605   17.677    2.26617   6.47276
1309120150014104855  1015001004920   19.619    2.27838 -16.68958
1309120150014104855  3017002016907   20.536    2.27892 -16.68959
1511301290014130643  1129001047389   18.763    2.29548  30.05226
1312251090014108455  2109003009450   13.246    2.31817   9.00876
1310120180014101233  3019002005376   14.735    2.32535 -19.70694
1310120180014101233  3019002005376   14.735    2.32535 -19.70694
1010070120014131116  1012001033373   19.754    2.40915 -12.17123
1010070120014131116  3013002017162   21.259    2.40957 -12.17185
911201400014137919   1140001049301   19.483    2.58039  41.08203
1408311210014119351  1121001023006   18.883    2.61967  20.79727
1201181320014109239  1132001013244   20.450    2.79361  31.50863
...                            ...      ...        ...       ...
1201141120454117896  1112045025393   19.638  126.97378  12.26665
1312241350384110624  1135038013918   18.910  127.11561  34.45465
1201131260424117626  2126106023651   12.155  127.45264  26.77431
1512060070464171296  1007046092728   18.938  127.77706  -5.71209
803051260424104243   2125108019228   21.775  127.80127  25.62406
1201021430344132418  1143034038538   20.060  128.02186  44.16830
1205221490314114861  1149031025208   17.733  128.09676  49.22273
1501221460334127130  1146033036694   20.814  128.67038  46.96607
1205201210444122117  2121112019538   17.826  129.07973  21.35145
902131090464114479   1109046019842   19.377  129.17403   9.23470
802031260424140087   1126042049102   20.625  129.21517  27.44356
802031260424140087   2127107009510   19.870  129.21564  27.44348
1204221520304126274  1152030035763   20.038  129.44315  52.33424
1304151070464118026  1107046025781   21.120  129.46097   6.60914
1012031380384133667  1138038042464   18.406  129.46246  38.50352
1505121150454142947  2116116017054   21.685  129.58140  16.84431
1003201120464144037  2113117026962   21.065  129.62992  14.01082
903021490314120932   1149031024627   18.050  129.68859  49.18241
903021490314120932   1149031024627   18.050  129.68859  49.18241
1610291630224109495  1163022013425   14.285  129.74604  62.67724
1411301350394111255  1135039014908   19.495  129.77670  34.53115
1311021290414104571  1129041005916   19.966  129.88037  28.47334
1311021290414104571  2128107006952   20.348  129.88060  28.47332
1303071520304144859  1152030054962   16.071  129.91778  53.14965
1411241150454102720  1115045004053   19.642  130.08225  14.25179
1411241150454102720  2114117004750   19.963  130.08239  14.25166
1005221090464126949  1109046049752   19.574  130.28347  10.42671
1202251320404143265  1132040053096   19.767  130.28994  33.28611
905251210444119239   1121044029353   19.957  130.36403  21.01498
905251210444119239   2121113011032   20.160  130.36407  21.01487

[4280 rows x 4 columns]